In [1]:
import sys
import scanpy as sc

print("Python:")
print(sys.executable)

print("\nScanpy:")
print(sc.__version__)

Python:
/Users/Tommy/Documents/GitHub/ImmunoType/.venv/bin/python3.12

Scanpy:
1.12.2

/var/folders/8g/sx7vtp551gv00j8kmvm1rl3w0000gq/T/ipykernel_24220/1753354158.py:8: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  print(sc.__version__)

In [2]:
adata = sc.datasets.pbmc3k()
adata
# 2700 cells x 32728 genes

AnnData object with n_obs × n_vars = 2700 × 32738
    var: 'gene_ids'
    layers: None (.X)

In [6]:
# inspect cell metadata
adata.obs.head()

Empty DataFrame
Columns: []
Index: [AAACATACAACCAC-1, AAACATTGAGCTAC-1, AAACATTGATCAGC-1, AAACCGTGCTTCCG-1, AAACCGTGTATGCG-1]

In [7]:
adata.obs.columns

Index([], dtype='str')

In [8]:
adata

AnnData object with n_obs × n_vars = 2700 × 32738
    var: 'gene_ids'
    layers: None (.X)

In [9]:
adata.uns.keys()

odict_keys([])

In [10]:
adata.var.head()

                     gene_ids
index
MIR1302-10    ENSG00000243485
FAM138A       ENSG00000237613
OR4F5         ENSG00000186092
RP11-34P13.7  ENSG00000238009
RP11-34P13.8  ENSG00000239945

In [11]:
adata.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 2286884 stored elements and shape (2700, 32738)>

In [12]:
type(adata.X)

scipy.sparse._csr.csr_matrix

In [13]:
adata.n_obs

2700

In [14]:
adata.n_vars

32738